language: node_js
node_js:
  - "10.15.3"

deploy_service_job: &DEPLOY_SERVICE_JOB

  install:
    - npm install -g serverless
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - sls deploy -v
    - cd -

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Frontend"
      env:
        - SERVICE_PATH="client"
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy backend"
      env:
        - SERVICE_PATH="backend"
