language: node_js
node_js:
  - "12.x"

# deploy_service_job: &DEPLOY_SERVICE_JOB
#   cache:
#     directories:
#       - node_modules
#       - ${SERVICE_PATH}/node_modules

#   install:
#     - npm install -g serverless
#     - cd ${SERVICE_PATH}
#     - travis_retry npm install
#     - cd -

#   script:
#     - cd ${SERVICE_PATH}
#     - serverless deploy -v
#     - cd -

# jobs:
#   include:
#     - <<: *DEPLOY_SERVICE_JOB
#       name: "Deploy Frontend"
#       env:
#         - SERVICE_PATH="client"
#     - <<: *DEPLOY_SERVICE_JOB
#       name: "Deploy backend"
#       env:
#         - SERVICE_PATH="backend"
